name: Build cmftStudio for Windows 64-bit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Visual Studio
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        version: 2013

    - name: Run Makefile for Visual Studio 2013
      run: |
        make vs2013-release64
