name: Build cmftStudio on Windows 64 (Mingw)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup MSYS2 environment
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >
            make
            mingw-w64-x86_64-gcc

      - name: Build using Makefile (Mingw release 64)
        run: |
          msys2 -c "cd \"$(cygpath -u \"$GITHUB_WORKSPACE\")\" && make -f Makefile mingw-gcc-release64"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: cmftStudio-binary
          path: _build/mingw64_gcc/bin/cmftStudioRelease
