name: Build cmftStudio for Windows 64 (Mingw)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup MSYS2 environment
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make
            make

      - name: Build using Makefile (Mingw release 64)
        run: msys2 -c "cd $GITHUB_WORKSPACE && make mingw-gcc-release64"
