name: Build Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup MSYS2 environment
        uses: msys2/setup-msys2@v2
        with:
          update: true

      - name: Print Workspace Directory (CMD)
        shell: cmd
        run: |
         echo "CMD Workspace Directory:"
         echo %GITHUB_WORKSPACE%

      - name: Print Workspace Directory (MSYS2)
        shell: msys {0}
        env:
          MSYSTEM: MINGW64
        run: |
          echo "MSYS2 Workspace Directory:"
          echo "$GITHUB_WORKSPACE"
