name: Build Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup MSYS2 environment
        uses: msys2/setup-msys2@v2
        with:
          update: true

      - name: Verify Workspace Directory
        run: |
          echo "$GITHUB_WORKSPACE"
